### ISSUE TITLE
Generate TypeScript types from JSDoc

### ISSUE THREAD

**Issue by gustavopch** [recombee/js-api-client#10]
I see that a good part of the source code already uses JSDoc. It's possible to generate TypeScript type definitions from JSDoc (https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html).

It'd be **very helpful for TypeScript users but also for JS users** because they would get better autocompletion in the editor.

It would also be possible to add static type checking to help maintainers (think of it as nothing more complex than linting) while still writing plain-old JavaScript (https://fettblog.eu/typescript-jsdoc-superpowers).

In order to do that, it would be necessary to:
- Install TypeScript as a dev dependency
- Set up `tsconfig.config.json` to output type definitions to a folder
- Point `package.json`'s `types` field to that output
- Perform minor JSDoc tweaks

What do you all think?

**Comment by scottbasgaard** [comment]
Types here would be great. I'm guessing @gustavopch they are looking into this now? https://github.com/recombee/node-api-client/issues/21

**Comment by pikl-cz** [comment]
We need types as well :-)

**Comment by vallpaper** [comment]
Hi everyone, we released SDK version 4.1.3 with full TS support. If you find any issue, please report it :)
