### ISSUE TITLE
AddUser request

### ISSUE THREAD

**Issue by jbtheard** [recombee/js-api-client#14]
How can we add a user as per https://docs.recombee.com/api.html#users ?

**Comment by OndraFiedler** [comment]
Hi @jbtheard,

The users are automatically created from the sent interactions.

**Comment by jbtheard** [comment]
But I want to be able to make a recommendation event before user has first interacted with any content! in such case request would throw because of user not existing. How am I supposed to do that ?

**Comment by jbtheard** [comment]
I may be the first one to state it but this API methods indeed has some interest !

**Comment by OndraFiedler** [comment]
> But I want to be able to make a recommendation event before user has first interacted with any content! in such case request would throw because of user not existing. How am I supposed to do that ?

Same as with the interactions, the user gets created on the first recommendation request with the given `userId` (because `cascadeCreate=true` by default in the JS client).

**Comment by jbtheard** [comment]
oh ok! I'll check that. Thanks for the quick answer.

**Comment by jbtheard** [comment]
oh that's actually because I do that first call on the backend...

**Comment by jbtheard** [comment]
I'll add cascadeCreate=true on the backend and that should be fixed
