### ISSUE TITLE
Provide Typescript example

### ISSUE THREAD

**Issue by jbtheard** [recombee/js-api-client#15]
it's unclear from your doc nor examples how to use typescript. It would be good to add snippet about it, and working example

**Comment by DanielBreiner** [comment]
Hi, thanks for the inquiry.
There's no extra setup necessary if you're using Typescript - the library is shipped with type definitions. You can use the provided classes and methods as normal and your code should be correctly typed.
We'll consider adding a short section about this to the readme.
