### ISSUE TITLE
File '.../node_modules/recombee-js-api-client/src/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by polgiron** [recombee/js-api-client#16]
Hello, I don't know what I am doing wrong, I am trying to import your sdk in my JS file and I am getting an error:

`File '.../node_modules/recombee-js-api-client/src/index.d.ts' is not a module.`

I've tried:
`import recombee from 'recombee-js-api-client'`
`import {recombee} from 'recombee-js-api-client'`
`require('recombee-js-api-client')`

I don't see anything in your documentation.

**Comment by OndraFiedler** [comment]
@polgiron Thanks for the report. The issue shall be fixed in v4.1.4.
