### ISSUE TITLE
Property 'AddDetailView' does not exist on type 'typeof import("node_modules/recombee-js-api-client/src/index")'

### ISSUE THREAD

**Issue by jmclellan-crexi** [recombee/js-api-client#18]
```
import recombee from 'recombee-js-api-client';

const recombeeRequest = new recombee.AddDetailView(
                "1",
                "123",
                { cascadeCreate: true, recommId }
);
```
![image](https://github.com/recombee/js-api-client/assets/113939147/03c2ceef-f382-4650-9e5c-34f0b94413cb)

Currently I am having to add the following to get around this error in typescript.

`// @ts-expect-error AddDetailView is not properly typed from the package`

**Comment by DanielBreiner** [comment]
You're completely right, this happened because we mistakenly used the same type definitions as in the Node.js SDK.
Sorry; we're working on a fix.

**Comment by DanielBreiner** [comment]
[v4.1.5](https://github.com/recombee/js-api-client/releases/tag/v4.1.5) which we just released should address this. I will close the issue for now - let me know if the problem persists.
