### ISSUE TITLE
ListUserBookmarks with new v4.1.5

### ISSUE THREAD

**Issue by polgiron** [recombee/js-api-client#19]
how do you use ListUserBookmarks with the new version of recombee v4.1.5 please?
can you please update your documentation?

```
var recombee = require('recombee-api-client');
var rqs = recombee.requests;

client.send(new rqs.ListUserBookmarks(userId))
.then((response) => {
    //handle response
})
.catch((error) => {
    //handle error
});
```

`var rqs = recombee.requests;` doesn't seem to exist
recombee is now imported in this way `import recombee from 'recombee-js-api-client'`

**Comment by DanielBreiner** [comment]
There are two Javascript SDKs - one for client-side integration and one for server-side integration. This repository belongs to the client-side SDK - the library is called `recombee-js-api-client` and it doesn't support destructive/transformative operations. If you need them, use the server-side SDK, called `recombee-api-client`, [link to repo](https://github.com/recombee/node-api-client).

You can see if an endpoint is available from the client SDK if it has an "Allowed on Client-Side" badge in https://docs.recombee.com/api. Depending on your use case, it might make sense to use `ListUserBookmarks` on client-side, in which case try contacting Recombee support at support@recombee.com.

**Comment by polgiron** [comment]
ok thanks for your answer, I didn't see this call should be made on the server side.
that's too bad as I would think listing bookmarks would not be a destructive or transformative operation.

**Comment by DanielBreiner** [comment]
You're right, but this particular endpoint is not exposed in the client-side SDKs for security reasons - if not implemented correctly, it could lead to sensitive data exposure.
