### ISSUE TITLE
MergeUsers endpoint is broken

### ISSUE THREAD

**Issue by panpanpandas** [recombee/js-api-client#3]
Merge users is a PUT method according to this doc: https://docs.recombee.com/api.html#merge-users

However, the library set POST method for all requests. 

https://github.com/recombee/js-api-client/blob/63484d7f0fb7a163dade6fa56b8772132e58c1cb/src/api-client.js#L45

**Comment by DanielBreiner** [comment]
The Javascript SDK is primarily used for operations which do not modify your database - you usually use it on the client-side with your public key.
It is possible to supply your private token (never expose publicly!), enabling you these requests.
Though undocumented, these will work using the POST method.
