### ISSUE TITLE
Deleting

### ISSUE THREAD

**Issue by Darlinkster** [recombee/js-api-client#6]
Why this client not support deleting for example Delete bookmark? Is there any reason for that?

**Comment by OndraFiedler** [comment]
As the Javascript SDK is used at frontend with `public token` for authentication, anyone would be able to call these actions.
In some cases (for example `userId`s not random) this would basically allow anyone to delete any data from the database.
Therefore these actions are allowed only from server side using `private token`.

**Comment by Darlinkster** [comment]
That make sence, thanks.
