### ISSUE TITLE
How to unify customer data?

### ISSUE THREAD

**Issue by mdings** [recombee/js-api-client#7]
In the example in the readme you are using the clientId coming from Google Analytics. 

` var userId = tracker.get('clientId'); // Get id from GA `

However this renders a new id on every new browser or device. How can I make sure that this data is being recognized as part of another user's interaction. I do have a user id once they login. Is merging the data inside Recombee enough to make this aggregation happen?

**Comment by OndraFiedler** [comment]
Yes, call the [Merge Users endpoint](https://docs.recombee.com/api.html#merge-users) and the interactions of the anonymous user will become interactions of the logged in user.
This endpoint should be called from the backend.
