### ISSUE TITLE
Filtering is not working!

### ISSUE THREAD

**Issue by fweffort** [recombee/js-api-client#9]
I have an item(X) that has a set of tags: {"foo","bar"}

and I have the user recomendation filtering by some other tags: {"bar","baz"}

I am currently using the following to filter

{{'tags'} & {"bar","baz"}} < {}

Which should resolve to true, and therefore return me this item(X) but it's not resolving correctly, it's returning even if the user has no tags at all that matches.

What is wrong with my filter?

**Comment by OndraFiedler** [comment]
If I correctly understand the purpose of the filter, there are two issues:

1) You are putting the set property 'tags' into another set, yielding `{{"foo","bar”}}`
2) You are asking if the result of the intersection (`&`) is a subset of an empty set, while you want to know if the intersection is non-empty

Please try: `size('tags' &  {"bar","baz"}) > 0`.

**Comment by fweffort** [comment]
Perfect. Thanks!!

Em sex., 12 de fev. de 2021 às 14:59, OndraFiedler <notifications@github.com>
escreveu:
